[package]
name = "yakshed-desktop-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
yakshed-application.workspace = true
yakshed-domain.workspace = true
tokio = { workspace = true }
url.workspace = true

[dev-dependencies]
async-trait.workspace = true
provider-mock.workspace = true
yakshed-harness.workspace = true
secrecy.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio = { workspace = true }
yakshed-secrets = { workspace = true, features = ["dev-secrets"] }
yakshed-store.workspace = true
