[package]
name = "yakshed-secrets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
secrecy.workspace = true
time.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }
yakshed-domain.workspace = true

[dev-dependencies]
serde_json.workspace = true
