[package]
name = "yakshed-contract-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
provider-mock.workspace = true
libc.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
yakshed-application.workspace = true
yakshed-domain.workspace = true
yakshed-harness.workspace = true
yakshed-secrets = { workspace = true, features = ["dev-secrets"] }
yakshed-store.workspace = true
