[package]
name = "yakshed-contract-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
provider-mock.workspace = true
yakshed-application.workspace = true
yakshed-desktop-api.workspace = true
yakshed-harness.workspace = true
yakshed-secrets.workspace = true
yakshed-store.workspace = true
