[package]
name = "yakshed-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
atomic-write-file.workspace = true
directories.workspace = true
rusqlite.workspace = true
rusqlite_migration.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
yakshed-application.workspace = true
yakshed-domain.workspace = true

[dev-dependencies]
tempfile.workspace = true
uuid.workspace = true
