[package]
name = "yakshed-application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
yakshed-domain.workspace = true

[dev-dependencies]
provider-mock.workspace = true
serde_json.workspace = true
tempfile.workspace = true
yakshed-harness.workspace = true
yakshed-store.workspace = true
